version: "3"

services:
  management:
    image: ghcr.io/apriorit/beegfs-demo-management
    hostname: node01
    networks:
      beegfs:
        aliases:
          - node01
          - management
    ports:
      - "8008:8008"
      - "8008:8008/udp"
  
  metadata:
    image: ghcr.io/apriorit/beegfs-demo-metadata
    hostname: node02
    networks:
      beegfs:
        aliases:
          - node02
          - metadata
    environment:
      METADATA_SERVICE_ID: 2
    ports:
      - "8005:8005"
      - "8005:8005/udp"
    depends_on:
      - management
  
  storage:
    image: ghcr.io/apriorit/beegfs-demo-storage
    hostname: node03
    networks:
      beegfs:
        aliases:
          - node03
          - storage
    environment:
      STORAGE_SERVICE_ID: 3
      STORAGE_TARGET_ID: 301
    ports:
      - "8003:8003"
      - "8003:8003/udp"
    volumes:
      - ~/beegfs_storage:/data
    depends_on:
      - management

networks:
  beegfs:
    driver: macvlan
    driver_opts:
      parent: # interface name, for example: ens33
    ipam:
      # macvlan can't use DHCP so we have provide network configuration manually
      config:
        - subnet: # interface subnet, for example: "192.168.1.0/24"
          ip_range: # ip range assigned to the services, for example: "192.168.1.64/30"
          gateway: # ip address of the gateway, for example: "192.168.1.1"
